import type { Metadata } from "next";
// 1. Import the font
import { Inter } from "next/font/google";
import "./globals.d.ts";

// 2. Configure the font
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* 3. Apply the font's className to the body */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}